### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by rohitnehra** [nicholaskajoh/faceclone#1]
Please provide database structure

**Comment by nicholaskajoh** [comment]
@rohitnehra thanks for the feedback. I'll add the DB structure to the repo in a bit. For now, check out the Part 2 of my tutorial for this project where I discuss the schema: https://medium.com/covenant-university-developers-community/build-a-facebook-clone-from-scratch-with-php-part-2-6a760bd30da3.
Cheers!

**Comment by nicholaskajoh** [comment]
I've added the schema with this commit: beb0a13. Sorry for the delay @rohitnehra.
