### ISSUE TITLE
this issue sucks

### ISSUE THREAD

**Issue by sgamesdev** [nicholaskajoh/faceclone#2]
when i try to register it says Error: Field 'status' doesn't have a default value

**Comment by nicholaskajoh** [comment]
Hey @edu1234567890, can you share the SQL schema for your users table? Run `DESCRIBE users;` against your DB.

**Comment by sgamesdev** [comment]
> Hey @edu1234567890, can you share the SQL schema for your users table? Run `DESCRIBE users;` against your DB.

I fixed the problem by checking the null option on status. It would be awsome if you beside the text, to can post images too
